show multiple rent types
bloom-housing/bloom pull request #1253
Opened 2021-05-19 18:50 UTC by emilyjablonski

# Pull Request Template
![Screen Shot 2021-05-19 at 12 43 39 PM](https://user-images.githubusercontent.com/65367387/118867811-b839b580-b8a0-11eb-8399-079e2bf6bcb0.png)
![Screen Shot 2021-05-19 at 12 42 11 PM](https://user-images.githubusercontent.com/65367387/118867816-b8d24c00-b8a0-11eb-813d-3e7bc9902d7d.png)

## Issue

Addresses # (issue)
- [ ] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

Please include a summary of the change and which issue is addressed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change requires a SQL Script

## How Can This Be Tested/Reviewed?

Please describe the tests that you ran to verify your changes. Provide instructions so we can review. Please also list any relevant details for your test configuration
- [ ] Desktop View
- [ ] Mobile View
- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers

2021-05-19 20:30 UTC, emilyjablonski commented on backend/core/src/shared/units-transformations.ts
> +  units.forEach((unit, index) => {
The diff is weird....this is the core change

2021-05-21 23:30 UTC, seanmalbert requested changes
Hey @emilyjablonski , for the most part the changes look good, though I do have concerns about the assumptions that the existing code and this had/have. It relies on units being grouped by type and since there isn't any logic (at least that I saw) to group them, it relies on them being inserted that way. I'm not against getting this in so people can review it, but I think we should refactor before it getting released to better handle grouping units together.

On the listing detail, Unit Features appears to have duplicates, which may be a result of how units are or are not getting grouped together.

I think what would make it easier is to have strict guidelines laid out of when units can be grouped together and then use that to create a map that could be easier to work with like:
```
unitMap: {
   [some composite key that takes into account unit type and other values]: Units[]
}
```

So, while I have requested changes here, if we're ok with merging for review sake, then we can come back to this with a refactor sometime before listing management gets released at the latest.

2021-05-21 23:30 UTC, seanmalbert commented on backend/core/src/shared/units-transformations.ts
> +  })
Can we rely on units being grouped in this way? I understand that's probably the case while we're manually uploading listings, but I don't think this is a long term solution.

2021-05-21 23:32 UTC, emilyjablonski commented
I also agree it's not the best long term solution to assume the groupings. I'll lean on your advice as to whether or not to merge as-is to move Coliseum along, or to refactor now.

2021-05-24 15:31 UTC, emilyjablonski commented
Refactoring in progress :)

2021-05-25 16:05 UTC, emilyjablonski commented
@seanmalbert Made the changes requested 👍

2021-05-26 01:24 UTC, seanmalbert requested changes
@emilyjablonski , nice work and we're almost there. A consequence of having rent type as part of the map key, which is necessary elsewhere, is that now the UnitTables component doesn't display units properly in the case of the Coliseum listing, because UnitTables, which is called by ListingView, takes `unitsSummarized.byUnitType` which now can have multiple entries for the same bedroom count. For example, instead of having one `unitSummary` for a one bedroom with a sq.ft. range of 486-491 and 4 units, we have two unit summaries for one bedrooms. One for 486 and one for 491 and because it filters the units in UnitTables by unitType, they both show four units. So it looks like there's a total of 8 one bedroom units 4 for each of the square footages.

There are many ways to address this. The two main pathways I see are one, to set another key in `transformUnits` to have units the way UnitTables expects them and pass that in, so you don't have to make any changes to UnitTables, and two, to make updates to UnitTables to handle the issue. Adding another key is likely the quickest and the least likely to break listings with units that don't fall into the same category as Coliseum.

Let me know if you need clarification on the changes.

2021-05-26 02:44 UTC, emilyjablonski commented
Good catch, I saw issues with occupancy which were caused by the exact same thing and fixed em, but didn't see the unit table ones :( I've pushed a refactor. There are now two unit-based summaries, one by just unit type (the old way), and one by both unit type and rent. So now I can revert the changes I made to occupancy and use the now-still-available "old" summaries there and in the unit table where you saw the issue, so those should display as they did before this PR. Elsewhere in the AMI chart and the unit overview I am using the new table that includes separate rows by rent. Let me know what you think and thank you for the thorough reviews!

2021-05-26 14:02 UTC, seanmalbert approved these changes
Thank you, @emilyjablonski , the updates look good to me!

2021-05-26 14:03 UTC, seanmalbert commented
@emilyjablonski ,

Sorry, one more thing, can you please add an entry to the changelog before merging?

2021-05-26 14:36 UTC, merged