feat: listings management, additional details section
bloom-housing/bloom pull request #1338
Opened 2021-06-08 22:08 UTC by emilyjablonski

# Pull Request Template

## Issue

Addresses # (issue)
- [ ] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

Please include a summary of the change and which issue is addressed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Prototype/POC (not to merge)
- [ ] This change is a refactor/address technical debt
- [ ] This change requires a documentation update
- [ ] This change requires a SQL Script

## How Can This Be Tested/Reviewed?

Please describe the tests that you ran to verify your changes. Provide instructions so we can review. Please also list any relevant details for your test configuration
- [ ] Desktop View
- [ ] Mobile View
- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have updated the changelog to include a description of my changes

2021-06-09 23:11 UTC, seanmalbert requested changes
@emilyjablonski ,

This looks good. In testing I found that I should have added a migration script for adding closed to the dbs listing status enum. So now if you reseed the db you should be all set. You can use `psql -d bloom -c "SELECT id FROM property;"` to grab a property id and add it to the form. After that I was able to successfully submit and view the new listing on the public site with the additional details section.

So all that's left is to do the work to hide the section if none of the fields have values.

2021-06-09 23:11 UTC, jaredcwhite approved these changes
Looks good to me :+1:

2021-06-11 01:34 UTC, emilyjablonski commented
@seanmalbert I rebased off of master, migrated, and re-seed, and am still seeing the missing `closed` on the enum when I try to submit, maybe I missed a step?

2021-06-11 18:00 UTC, emilyjablonski commented
Removed selection criteria because I realized that field in the json is currently only used as a link that shows under the occupancy table, not as a text box. Reached out to design to confirm that that whole box can be removed from this section. Tested with new properties, and added the details page. The three sections already don't show if they're empty, so pending design feedback I think we are g2g.

2021-06-11 18:25 UTC, emilyjablonski commented
Confirmed removing selection criteria, so ready for review again :)

2021-06-11 19:59 UTC, seanmalbert approved these changes
Thanks for the updates @emilyjablonski , looks good to me!

2021-06-11 20:46 UTC, merged