1430/listings management, fcfs and lottery
bloom-housing/bloom pull request #1485
Opened 2021-07-07 19:39 UTC by emilyjablonski

# Pull Request Template

## Issue

Addresses # (issue)
- [ ] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

Please include a summary of the change and which issue is addressed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Prototype/POC (not to merge)
- [ ] This change is a refactor/address technical debt
- [ ] This change requires a documentation update
- [ ] This change requires a SQL Script

## How Can This Be Tested/Reviewed?

Please describe the tests that you ran to verify your changes. Provide instructions so we can review. Please also list any relevant details for your test configuration
- [ ] Desktop View
- [ ] Mobile View
- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have updated the changelog to include a description of my changes

2021-07-08 20:36 UTC, emilyjablonski commented
Large prettier diff is making it hard to review, taking a look at that

2021-07-14 20:51 UTC, seanmalbert requested changes
@emilyjablonski ,
Overall this looks good. The main change that's needed is how reviewOrderType is defined in the backend. Please see my comment on that. 

My machine is probably a little slow at the moment, but it does seem to take a long time to switch between the first come first serve and lottery options in the form. If it seems a little slow to you too, consider moving those pieces to a memoized component(s).

2021-07-14 20:51 UTC, seanmalbert commented on backend/core/src/listings/entities/listing.entity.ts
> +
I think this should be moved to the listing DTO. See the other definitions in there with the `@Transform` decorator. Also, with the way it is now generate client doesn't properly add `reviewOrderType` or `ListingReviewOrder`, which causes issues, so the definition should include `reviewOrderType: ListingReviewOrder`.

2021-07-15 09:06 UTC, pbn4 commented
@emilyjablonski Could you please try to revert the formatting commits? I can make it a separate PR.

2021-07-15 23:54 UTC, closed without merging