1455/language tabs a11y
bloom-housing/bloom pull request #1528
Opened 2021-07-19 12:36 UTC by dominikx96

# Pull Request Template

## Issue
Closes: #1455

Addresses # (issue)
- [x] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description
Updated list elements to buttons - now these items are focusable and visible for screen readers.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Prototype/POC (not to merge)
- [ ] This change is a refactor/address technical debt
- [ ] This change requires a documentation update
- [ ] This change requires a SQL Script

## How Can This Be Tested/Reviewed?

1. Open the home page
2. Try to choose a different language using the keyboard

- [x] Desktop View
- [x] Mobile View

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [x] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have assigned reviewers
- [x] I have updated the changelog to include a description of my changes

2021-07-20 19:46 UTC, emilyjablonski approved these changes
LGTM

2021-07-21 22:25 UTC, seanmalbert commented
@akegan ,
When you get a chance, can you please review.

2021-07-21 23:57 UTC, akegan requested changes
LGTM on the homepage and code, but I'm seeing this error [on the storybook preview site](https://deploy-preview-1528--dev-storybook-bloom.netlify.app/?path=/story/navigation-languagenav--default)

![image](https://user-images.githubusercontent.com/11825994/126573912-107f4ee7-9879-4403-902a-4e6e44d8f5b9.png)

I actually see the same issue on [storybook.bloom.exygy.dev](https://storybook.bloom.exygy.dev/?path=/story/navigation-languagenav--default), so if you think it's out of scope to fix in this PR I can approve as-is, however, it'd also be nice if the a11y tests could run on this component which requires a working storybook story.

2021-07-23 16:08 UTC, dominikx96 commented
@akegan I've fixed the storybook component, can you make sure that everything works as expected? Thanks!

2021-07-23 17:04 UTC, akegan approved these changes
LGTM, thanks for fixing the storybook component! 
![image](https://user-images.githubusercontent.com/11825994/126816796-53c54400-58a8-4a18-a8b7-78e165f0dbbb.png)

2021-07-23 22:03 UTC, merged