1713/remove business logic from appStatusItem component
bloom-housing/bloom pull request #1714
Opened 2021-08-24 15:20 UTC by emilyjablonski

# Pull Request Template

## Issue

Addresses # (issue)

- [ ] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

Please include a summary of the change and which issue is addressed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Prototype/POC (not to merge)
- [ ] This change is a refactor/address technical debt
- [ ] This change requires a documentation update
- [ ] This change requires a SQL Script

## How Can This Be Tested/Reviewed?

Please describe the tests that you ran to verify your changes. Provide instructions so we can review. Please also list any relevant details for your test configuration

- [ ] Desktop View
- [ ] Mobile View
- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have updated the changelog to include a description of my changes

2021-08-31 00:11 UTC, jaredcwhite requested changes
Just one deprecation to look at and a general question, otherwise looks good to me. :+1:

2021-08-31 00:11 UTC, jaredcwhite commented on ui-components/src/blocks/AppStatusItem.tsx
> +            <LocalizedLink className="status-item__link lined" href={props.listingURL}>
FYI, LocalizedLink is deprecated and we should probably remove it soon. Best to use `LinkComponent` from the `NavigationContext` instead. (See the `LinkButton` component for example usage.)

2021-08-31 00:11 UTC, jaredcwhite commented on ui-components/src/blocks/AppStatusItem.tsx
>  const AppStatusItem = (props: AppStatusItemProps) => {
I wonder if we should rename this and the props as well to something even more generic like just `StatusItem`. That's what the CSS class names are already.

2021-09-09 05:51 UTC, seanmalbert approved these changes
Looks good to me, @jaredcwhite , can you take another look since the updates.

2021-09-10 17:02 UTC, emilyjablonski commented
@jaredcwhite

2021-09-13 18:56 UTC, jaredcwhite approved these changes
LGTM :+1:

2021-09-13 21:12 UTC, merged