1653/user invite flow frontend
bloom-housing/bloom pull request #1857
Opened 2021-09-21 15:09 UTC by dominikx96

# Pull Request Template

## Issue

Addresses #1653

- [x] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

Please include a summary of the change and which issue is addressed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Prototype/POC (not to merge)
- [ ] This change is a refactor/address technical debt
- [ ] This change requires a documentation update
- [ ] This change requires a SQL Script

## How Can This Be Tested/Reviewed?

Please describe the tests that you ran to verify your changes. Provide instructions so we can review. Please also list any relevant details for your test configuration

- [ ] Desktop View
- [ ] Mobile View
- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have updated the changelog to include a description of my changes
- [ ] I have run `yarn generate:client` if I made backend changes

2021-09-23 19:42 UTC, emilyjablonski commented
Small typo in the e-mail `To complete your account creation, please the link below:` just need the word `click`.
Also it seems kinda weird to me that the email says `It will now be easier for you to start, save, and submit online applications for listings that appear on the site.` when we're inviting partners? Might be a product question bc I know that's straight from the issue.

2021-09-23 19:43 UTC, emilyjablonski requested changes
Small typo in the e-mail `To complete your account creation, please the link below:` just need the word `click`.
The e-mail subject should be `Welcome to the Partners Portal` and the content is a little different, but it's in the issue :)

2021-09-23 19:47 UTC, emilyjablonski commented
When I click "Confirm my Account" from the email I'm taken to the partners sign-in page but I don't have a password yet so I'm not sure what the flow there should be. Maybe the "create a password" flow is a separate issue?

2021-09-23 19:49 UTC, emilyjablonski commented on sites/partners/pages/users/index.tsx
> +  /* Fetch listings */
@seanmalbert Might eventually be worth a new query that only retrieves name, jurisdiction, and ID

2021-09-23 19:49 UTC, emilyjablonski commented on sites/partners/src/users/FormUserAdd.tsx
> +      leasingAgentInListings: leasingAgentInListings,
NB but don't need the colons here

2021-09-27 19:18 UTC, emilyjablonski commented
I'm curious about my two comments above still - the content of the email is not quite right and the fact that I am redirected to sign-in without having set up a password (which is maybe a later ticket?)

2021-09-27 19:24 UTC, kathyccheng commented
@emilyjablonski Flow for leasing agents to update their password is in a separate issue, https://github.com/bloom-housing/bloom/issues/1654

Email copy from issues re-pasted below for reference :) 

**Email Copy**

From: no-reply@housingbayarea.org
Subject Line: Welcome to the Partners Portal

Hello Name,

Welcome to the the Partners Portal on [URL]. You will now be able to manage listings and applications that you are a part of from one centralized location.

To complete your account creation, please click the link below:

Confirm my account

Thank you,
Alameda County - Housing and Community Development (HCD) Department

2021-09-28 15:42 UTC, dominikx96 commented
@emilyjablonski I updated translations and resolved conflict in the `FieldGroup` component, ready for review :)

2021-09-28 15:42 UTC, emilyjablonski commented on backend/core/src/migration/1631110073158-add-null-jurisdiction-translation.ts
> +        "Welcome to the the Partners Portal on %{appUrl}. You will now be able to manage listings and applications that you are a part of from one centralized location.",
One small typo here `the the`

2021-09-28 15:43 UTC, emilyjablonski commented
I get a 400 if I try to add a user who already exists which I think is probably okay, but it means if anyone has ever created an account on the public site they we can't add them as a user on the partners site with the same email.

2021-09-28 15:48 UTC, dominikx96 commented on backend/core/src/migration/1631110073158-add-null-jurisdiction-translation.ts
> +        "Welcome to the the Partners Portal on %{appUrl}. You will now be able to manage listings and applications that you are a part of from one centralized location.",
Thanks, fixed! :)

2021-09-28 15:55 UTC, emilyjablonski approved these changes
LGTM apart from the existing user piece and it sounds like that's a separate PR :)

2021-09-29 03:50 UTC, seanmalbert commented
@pbn4 , see Emily's comment above, can you fix the issue causing the 400 bad request to be thrown when a user who already exists in the system gets added. A more useful response is probably all that's needed, something like `A user with that email already exists`.

2021-09-30 07:47 UTC, merged