Preferences cleanup
bloom-housing/bloom pull request #1947
Opened 2021-10-06 15:08 UTC by pbn4

# Pull Request Template

## Issue

Addresses # (#1837 )

- [ ] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

Please include a summary of the change and which issue is addressed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Prototype/POC (not to merge)
- [ ] This change is a refactor/address technical debt
- [ ] This change requires a documentation update
- [ ] This change requires a SQL Script

## How Can This Be Tested/Reviewed?

Please describe the tests that you ran to verify your changes. Provide instructions so we can review. Please also list any relevant details for your test configuration

- [ ] Desktop View
- [ ] Mobile View
- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have updated the changelog to include a description of my changes
- [ ] I have run `yarn generate:client` if I made backend changes

2021-10-13 20:23 UTC, emilyjablonski commented on backend/core/src/preferences/preferences.service.ts
> +  list(params?: PreferencesListQueryParams): Promise<Preference[]> {
How do I fetch preferences if a user has more than one jurisdiction?

2021-10-20 04:38 UTC, seanmalbert requested changes
@pbn4 and @emilyjablonski ,
There are two pieces that seem off:

1. In partners, if I remove preferences and add them to a listing `listingPreference.page` becomes null, which means they won't show up on the application. We don't have a UI for setting the page of a selected preference, and until we do, we may need to keep a page column on `preferences` too, so we can set that on `listings_preferences` when adding to a listing. We should bring this up in stand-up, but it may be the best solution until we have an improved UI for adding preferences on a listing
2. This next one isn't a bug, but I want to call it out here along with item 1. When adding a preference to a listing and once it's added, there isn't any indication in partners that the preference will be hidden on the listing detail. Even once we have a UI for adding preferences, it would be nice to have an indicator on the LM form/detail that the preference will be hidden.

2021-10-20 17:18 UTC, seanmalbert commented
As discussed, we're going to keep pages for now and we need to update the LM form, so that the listingPreferences getting set are using the page value from the preference, so that preferences show on the application. In a separate issue, we are going to remove pages and update the application to split preferences across pages based off their ordinal.

2021-10-20 22:25 UTC, emilyjablonski commented
@pbn4 had some significant backend merge conflicts w the new jurisdiction language piece but i think i resolved them ok

2021-10-30 00:33 UTC, seanmalbert commented
removed the no longer needed test and updated others, since preferences are no longer on the same page.

2021-10-30 00:33 UTC, merged