1916/refactor listing form
bloom-housing/bloom pull request #2012
Opened 2021-10-16 00:06 UTC by jaredcwhite

# Pull Request Template

## Issue

Addresses #issue

- [ ] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

Please include a summary of the change and which issue(s) is addressed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Prototype/POC (not to merge)
- [ ] This change is a refactor/addresses technical debt
- [ ] This change requires a documentation update
- [ ] This change requires a SQL Script

## How Can This Be Tested/Reviewed?

Provide instructions so we can review.

Describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have updated the changelog to include a description of my changes
- [ ] I have run `yarn generate:client` if I made backend changes
- [ ] I have exported any new pieces in ui-components

2021-11-09 14:55 UTC, emilyjablonski commented
This code is much cleaner and separated, thank you! I think overall I am finding the move to the class with individual formatters to be more confusing to read than how it was before though. Can you outline what you think the benefits are of this being the class/formatter type?

2021-11-10 13:24 UTC, dominikx96 requested changes
@jaredcwhite I noticed a problem with open houses, I've filled out the whole form, but values (date, start, end) don't exist - on dev it works as expected, see:

![Partners Portal 2021-11-10 at 2 05 23 PM](https://user-images.githubusercontent.com/16655908/141120985-16593170-6162-4104-aabb-c09039f1d7be.jpg)

2021-11-11 21:40 UTC, jaredcwhite commented on sites/partners/src/listings/PaperListingForm/formatters/BooleansFormatter.ts
> +import Formatter from "./Formatter"
I was hoping to find a way to cut down the repetition here, but I wasn't able to find a fool-proof solution. Before it was a just a lot of nested ternary operators which is pretty gnarly, so this is at least a little more obvious what's happening. Happy for any suggestions on how to improve…

2021-11-11 21:48 UTC, jaredcwhite commented
> This code is much cleaner and separated, thank you! I think overall I am finding the move to the class with individual formatters to be more confusing to read than how it was before though. Can you outline what you think the benefits are of this being the class/formatter type?

@emilyjablonski Sure, so the first win would be that adding new formatters is trivial — just add a new file in `formatters` that subclasses `Formatter` and modifies `this.data` in some way, add a single new `import` to `ListingDataPipeline`, and the rest falls into place automatically. In addition, any shared logic (like `processBoolean`) can be added to `Formatter` directly and then all the subclasses would inherit that logic.

The second win is because we have standalone formatters, they can all be unit tested independently of each other. I didn't completely fill out the tests yet in this PR, but it's a decent part of the way done.

The third, downstream win is we can apply a similar pattern anywhere else in the frontend codebase where such a data pipeline is required.

If there are any particular areas which are hard to parse in the new structure, feel free to suggest what you'd like to see improved.

2021-11-16 16:56 UTC, emilyjablonski commented
@jaredcwhite Do you mind checking out Dominik's comment above?

2021-11-30 22:30 UTC, emilyjablonski commented
@jaredcwhite Another bump :)

2021-11-30 23:26 UTC, jaredcwhite commented
Yep, I can work on refreshing this now that we have a bunch of new form stuff merged into dev.

2021-12-02 04:22 UTC, jaredcwhite commented on sites/partners/src/listings/PaperListingForm/formatters/BooleansFormatter.ts
> +        this.data.whereApplicationsPickedUp === addressTypes.anotherAddress,
Yes, good catch!

2021-12-02 04:25 UTC, jaredcwhite commented
> @jaredcwhite I noticed a problem with open houses, I've filled out the whole form, but values (date, start, end) don't exist - on dev it works as expected, see:
> 
> ![Partners Portal 2021-11-10 at 2 05 23 PM](https://user-images.githubusercontent.com/16655908/141120985-16593170-6162-4104-aabb-c09039f1d7be.jpg)

@dominikx96 I'm seeing an issue with date parsing in general now, just for the open houses, and it's on dev too! 😬 Look here:

<img width="892" alt="Screen Shot 2021-12-01 at 8 13 08 PM" src="https://user-images.githubusercontent.com/658496/144357428-8f2f9332-a911-492f-9238-80ab92c25a84.png">

2021-12-02 22:06 UTC, jaredcwhite commented
Welp, there's another issue with open house events that's on dev! #2265

2022-01-04 17:13 UTC, seanmalbert commented on sites/partners/src/listings/PaperListingForm/formatters/BooleansFormatter.ts
> +import Formatter from "./Formatter"
I think I'm good with this too, any abstraction to reduce repetition would probably make it more difficult to modify or at least read.

2022-01-04 17:39 UTC, seanmalbert approved these changes
This looks good, @jaredcwhite! I think there's an issue with units not persisting in the case of a new listing and field validation failing on publish, but I don't think it's related to this.

2022-01-04 17:44 UTC, merged