fix: Incorrect listing status
bloom-housing/bloom pull request #2015
Opened 2021-10-18 10:20 UTC by dominikx96

# Pull Request Template

## Issue

Addresses #1949

- [x] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

Fixes incorrect status (closed) if the application due date is before the current time even if the application is a draft.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Prototype/POC (not to merge)
- [ ] This change is a refactor/addresses technical debt
- [ ] This change requires a documentation update
- [ ] This change requires a SQL Script

## How Can This Be Tested/Reviewed?

Try to create a new listing with a past due date ad try to save it as a draft. After saving, a status still should be `draft`;

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have assigned reviewers
- [x] I have updated the changelog to include a description of my changes
- [ ] I have run `yarn generate:client` if I made backend changes
- [ ] I have exported any new pieces in ui-components

2021-10-20 05:55 UTC, seanmalbert requested changes
@dominikx96 , please see @emilyjablonski's comment

2021-10-20 09:26 UTC, dominikx96 commented
> From what's in the issue this looks good but I cannot get back from the Closed state. So if I make a draft listing with a due date in the past this branch still keeps it as a draft which is good. Then I publish it and its closed which makes sense. Then I change the due date to the future and save but it is still closed. It shows up in the closed section in the website but its due date is in the future.

Hm when I click the "Publish" button, a listing is active again. This behavior is only when you click on the "Save and exit" button.

How do we want to resolve it? I think when a listing is closed, you should use `Publish` to change the status to `active` even if a `dueDate` is future. Maybe we should consider changing status to `pending` when:

- listing is closed
- user tries to use the `Save and exit` button

@emilyjablonski @seanmalbert

2021-10-20 19:24 UTC, emilyjablonski commented
@dominikx96 Just putting a note here from what we talked about in standup - when a listing is Closed and we change the due date to the future and hit save as draft, the status should be published

2021-10-22 00:40 UTC, emilyjablonski commented
Getting this on the listing/add page I think you just need an optional
<img width="996" alt="Screen Shot 2021-10-21 at 6 39 45 PM" src="https://user-images.githubusercontent.com/65367387/138375357-da4e5efc-7943-4b78-bead-92ec576fd4c7.png">

2021-10-26 06:30 UTC, merged