fix: cannot save custom mailing, dropoff, or pickup address
bloom-housing/bloom pull request #2207
Opened 2021-11-20 00:02 UTC by emilyjablonski

# Pull Request Template

## Issue Overview

This PR addresses #2018

- [x] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

Couldnot save custom mailing, dropoff, or pickup address in LM.

## How Can This Be Tested/Reviewed?

Attempt to save mailing, dropoff, and pickup address of all types, ensure when you re-open the listing the address section is in the proper state.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ x I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [x] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

2021-11-23 15:25 UTC, dominikx96 requested changes
These changes look good to me! I've just noticed a problem with a `state` validation in the Pickup Address (not sure about the dropoff section). I tried to save the listing as a draft, but I got an error from the backend, but I didn't see any UI error message:

![Partners Portal 2021-11-23 at 4 17 47 PM](https://user-images.githubusercontent.com/16655908/143052480-39416906-532a-4e26-a027-8e010eecfe40.jpg)

![Partners Portal 2021-11-23 at 4 17 55 PM](https://user-images.githubusercontent.com/16655908/143052506-551d54ee-8ada-435a-92bb-536abf227251.jpg)

I think we should remove (or modify) the validator because it's a draft (?)

2021-11-23 18:15 UTC, emilyjablonski commented
@dominikx96 Great catch thank you, I'll take a look / also ask design

2021-11-23 21:25 UTC, emilyjablonski commented
Long term desired behavior is that for any address field, even if the general address is not a required field (like pick up or drop off or mailing address) that if a user inputs at least one of the required address fields (street, city, state, zip) that it will not let you save without filling out all the address fields.

I made a separate ticket for that and just fixed here the fact that it wouldn't let you submit with partial fields.

2021-11-24 08:52 UTC, dominikx96 approved these changes

2021-11-29 15:39 UTC, seanmalbert approved these changes

2021-11-29 16:35 UTC, merged