feat(backend): add partners portal users multi factor authentication
bloom-housing/bloom pull request #2291
Opened 2021-12-08 16:12 UTC by pbn4

# Pull Request Template

## Issue Overview

This PR addresses #2244 

- [ ] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

Please include a summary of the change and which issue(s) is addressed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## How Can This Be Tested/Reviewed?

Provide instructions so we can review.

Describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

2021-12-15 00:12 UTC, emilyjablonski commented
What do you think is the best way to test this PR?

2021-12-20 11:36 UTC, pbn4 commented
> What do you think is the best way to test this PR?

Good question. It's pure API change so it's doable e.g. by postman or an autogenerated JS client. Try following e2e test scenario [here](https://github.com/bloom-housing/bloom/pull/2291/files#diff-bbfd947f74508795ca57e30a4d194d5053a08828ee3fd38d4b4ce2068b54228fR794) which basically retrieves MFA information for a given user and then provides MFA credentials. The important part is that your user must have `mfa_enabled` equal to true in `user_accounts` table in the DB. 

Testing an SMS requires setting up few environment variables when running backend (cc: @seanmalbert, could you provide those, please?): TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN, TWILIO_PHONE_NUMBER.

2021-12-22 07:18 UTC, seanmalbert commented
> Testing an SMS requires setting up few environment variables when running backend (cc: @seanmalbert, could you provide those, please?): TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN, TWILIO_PHONE_NUMBER.

I added these to the dev backend settings in heroku.

2022-01-06 18:22 UTC, YazeedLoonat requested changes
This looks good, just a few small changes/suggestions

for anyone else that wants to test this, you'll need to work with sean to get your phone number verified for the test phone number to send an sms to you

2022-01-06 18:22 UTC, YazeedLoonat commented on backend/core/src/auth/dto/request-mfa-code.dto.ts
> +  @IsPhoneNumber(null, { groups: [ValidationsGroupsEnum.default] })
This seems to conflict with how twillio handles phone number formats for us domestic numbers. I think we should probably remove it

2022-01-19 16:17 UTC, YazeedLoonat approved these changes
LGTM

2022-02-15 08:00 UTC, merged