2328/address verification
bloom-housing/bloom pull request #2412
Opened 2022-01-17 21:59 UTC by jaredcwhite

## Issue Overview

This PR addresses #2328 

- [x] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

Please include a summary of the change and which issue(s) is addressed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## How Can This Be Tested/Reviewed?

Provide instructions so we can review.

Describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

2022-01-18 21:07 UTC, jaredcwhite commented
A couple of notes:

* The partners test is failing due to another issue that (is? was?) on dev, not affected by this PR.
* The git diff in the "Files changed" is really weird, most of the stuff that looks changed isn't actually, it just got added to a conditional block. Subsequently I'm pretty sure most if not all of the accessibility warnings are bogus.

2022-01-19 08:52 UTC, dominikx96 commented
@jaredcwhite this works good to me, we just need to remember about this before merging: https://github.com/bloom-housing/bloom/issues/2328#issuecomment-1015830050

The second question is - when a user selects an option generated by Mapbox geocoder, maybe we should also save latitude and longitude?

2022-01-19 16:07 UTC, YazeedLoonat requested changes
Looks good to me, just a question on here, and can you please add QA notes to the issue

2022-01-20 03:14 UTC, jaredcwhite commented on sites/public/src/forms/applications/ValidateAddress.tsx
> +      const [street, city, region] = response.body.features[0].place_name.split(", ")
I tried a wide variety of inputs including completely garbage text, and the most it ever came back funky I was able to detect due to a missing Zip code (which is is part of that code block), so I think we're OK here. Their "fuzzy search" is indeed very fuzzy 😄

2022-01-20 03:15 UTC, jaredcwhite commented
> The second question is - when a user selects an option generated by Mapbox geocoder, maybe we should also save latitude and longitude?

@dominikx96 I'm not sure, I don't know if we need lat/lng for applications. Isn't that just for listings?

2022-01-21 06:14 UTC, seanmalbert commented
> > The second question is - when a user selects an option generated by Mapbox geocoder, maybe we should also save latitude and longitude?
> 
> @dominikx96 I'm not sure, I don't know if we need lat/lng for applications. Isn't that just for listings?

I do not think we need to save the coordinates of the applicants address.

2022-01-24 16:29 UTC, seanmalbert requested changes
@jaredcwhite ,
This looks good. Can you add in a test with garbage address info, that way if the API becomes less fuzzy for whatever reason, we'll be able to catch it sooner. I was also wondering about if it made sense to set the country to always be the U.S. for the API call. I think this might cut out a lot of the fuzziness we're seeing.

2022-01-24 19:20 UTC, seanmalbert commented
@jaredcwhite ,
I asked @kathyccheng about always setting US as the country when calling the API and she thinks that's a viable option. Can you update this to be the case along with a test or two with garbage data.

2022-01-24 22:14 UTC, jaredcwhite commented
@seanmalbert Sounds good, I'll add the country in the search query code, as well as see if I can expand the E2E test with a couple rounds of varied data entry.

2022-01-25 22:27 UTC, jaredcwhite commented
OK, I discussed with Jesse and now the error state looks better (see https://github.com/bloom-housing/bloom/issues/2328#issuecomment-1021667122)…think this is ready to merge now.

2022-01-26 01:20 UTC, seanmalbert approved these changes

2022-01-26 01:20 UTC, merged