2382/berkeley way customizations
bloom-housing/bloom pull request #2436
Opened 2022-01-26 20:03 UTC by YazeedLoonat

## Issue Overview

This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/2382)

- [x] This change addresses the issue in full

## Description
This adds a program and preference for berkeley way 

## How Can This Be Tested/Reviewed?
run the following postgres
```
INSERT INTO preferences (Title, subtitle, description, links, form_metadata)
SELECT 
    'Live or Work in the County of Alameda' as Title,
    '' as subtitle,
    'At least one member of my household lives or works in the County of Alameda' as description,
    '[]' as links,
    '{"key":"alamedaLive","options":[{"key":"live","extraData":[],"description":false},{"key":"work","extraData":[],"description":false}]}' as form_metadata
;

SELECT
    *
FROM preferences
WHERE title = 'Live or Work in the County of Alameda'
;

SELECT
    *
FROM jurisdictions
WHERE name = 'Alameda'
;

INSERT INTO jurisdictions_preferences_preferences
SELECT '35416f6e-d580-48e9-9ed6-e7ce788a62f1' as jurisdictions_id,
'03851fff-6a3e-42f4-9ebe-977142a080f6' as preferences_id
;

INSERT INTO programs (Title, subtitle, description, form_metadata)
SELECT 
    'Flat Rent & Rent Based on Income' as Title,
    'This property includes two types of affordable housing programs. You can choose to apply for one or both programs. Each program will have its own applicant list. Your choice will tell us which list(s) to put your name on. Additional information on each of the two types of housing opportunities are below.' as subtitle,
    'Do you want to apply for apartments with flat rent and rent based on income?' as description,
    '{"key":"rentBasedOnIncome","options":[{"key":"flatRent","extraData":[],"description":true},{"key":"30Percent","extraData":[],"description":true}]}' as form_metadata
;

SELECT 
    *
FROM programs
WHERE Title = 'Flat Rent & Rent Based on Income'
;

INSERT INTO jurisdictions_programs_programs
SELECT '35416f6e-d580-48e9-9ed6-e7ce788a62f1' as jurisdictions_id,
'5f7b5ace-e6ba-4a24-9a55-7d0a12f89f5b' as programs_id
;

```

then add that program and preference to a listing then test it out
## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

2022-01-31 17:31 UTC, YazeedLoonat commented
@emilyjablonski good call, got that updated

2022-02-01 06:01 UTC, seanmalbert requested changes
@YazeedLoonat ,

Can you make the type enumerable with "checkbox" and "radio" as the options. Otherwise, this looks good to me.

2022-02-01 17:51 UTC, YazeedLoonat commented
Hey @seanmalbert got this updated, lemme know what you think

2022-02-01 21:12 UTC, emilyjablonski requested changes
Adding the seed, commented above

2022-02-01 22:03 UTC, YazeedLoonat commented
@emilyjablonski added!

2022-02-01 23:10 UTC, emilyjablonski commented
@YazeedLoonat You'll need to update the Cypress test

2022-02-02 05:23 UTC, seanmalbert requested changes

2022-02-02 05:23 UTC, seanmalbert commented on shared-helpers/src/programHelpers.ts
> +  if (program?.formMetadata?.type === "checkbox") {
Please update this to use the new enum, e.i `program?.formMetadata?.type === FormMetaDataType.checkbox`

2022-02-02 05:23 UTC, seanmalbert commented on backend/core/types/src/backend-swagger.ts
> +  type: string
I think you need to run generate:client since the type update.

2022-02-02 05:23 UTC, seanmalbert commented on sites/public/pages/applications/household/programs.tsx
> +                      type={pageProgram?.formMetadata?.type || "radio"}
Like above, please update to use the enum.

2022-02-02 18:10 UTC, emilyjablonski commented
![Screen Shot 2022-02-02 at 11 09 10 AM](https://user-images.githubusercontent.com/65367387/152212506-afd6db95-f57a-4a8d-96de-bca1d0568ccd.png)
I can select both even though it says "select one" is that expected?

2022-02-02 18:12 UTC, emilyjablonski commented
![Screen Shot 2022-02-02 at 11 12 14 AM](https://user-images.githubusercontent.com/65367387/152212849-7b87891d-12be-4244-9a6e-667ce484b4a1.png)
Additionally if I try and change the value of the entry in the partners application edit page I get this error

2022-02-02 18:14 UTC, emilyjablonski commented
![Screen Shot 2022-02-02 at 11 14 07 AM](https://user-images.githubusercontent.com/65367387/152213167-f15737c8-d982-4326-a256-596963bff2dc.png)
I also find the CSV export columns to be confusing as to what is selected

2022-02-02 19:03 UTC, seanmalbert approved these changes
@YazeedLoonat ,

LGTM, aside from what @emilyjablonski called out. Once that's covered and she approves it, I think it's good to merge and move over to QA.

2022-02-02 22:28 UTC, emilyjablonski approved these changes
LGTM once the partners netlify job passes :)

2022-02-02 22:56 UTC, seanmalbert commented
For some reason, github is showing the tests are still running, but circleci is showing them as passed, so we're good to merge.

2022-02-02 22:56 UTC, merged