1928/adding-mfa-to-partners-portal
bloom-housing/bloom pull request #2461
Opened 2022-02-01 21:36 UTC by YazeedLoonat

## Issue Overview

This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/1928)

- [x] This change addresses the issue in full

## Description
This adds MFA to the partners portal

## How Can This Be Tested/Reviewed?
Step 1: create a user that has mfaEnabled (there is currently no way to set this via the front end, but creating a new user should do it) 
Step 2: attempt to log in as that user, you should have to go through the new MFA steps
Step 3: in order to test this with an sms you will need to talk to @seanmalbert to get your phone number added as a verified test number

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [x] I have reviewed the changes in a mobile view
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [x] I have exported any new pieces added to ui-components
- [x] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [x] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

2022-02-04 16:34 UTC, seanmalbert requested changes

2022-02-04 16:34 UTC, seanmalbert commented on sites/partners/pages/sign-in.tsx
> +      }
Can update to handle if its a different error than `phoneNumberMissing`

2022-02-04 16:34 UTC, seanmalbert commented on sites/partners/pages/sign-in.tsx
> +  const onSubmitMfaCode = useCallback(
It may make sense to move the onSubmitMfa handlers to a separate mfa helpers file under lib

2022-02-04 16:34 UTC, seanmalbert commented on ui-components/src/page_components/sign-in/FormSignInAddPhone.tsx
> +        <ErrorMessage id={"householdsize-error"} error={!!networkError.error}>
Update id

2022-02-04 16:34 UTC, seanmalbert commented on ui-components/src/page_components/sign-in/FormSignInMFACode.tsx
> +        <ErrorMessage id={"householdsize-error"} error={!!networkError.error}>
repeated

2022-02-04 16:34 UTC, seanmalbert commented on ui-components/src/page_components/sign-in/FormSignInMFAType.tsx
> +      )}
This section is repeated three different times, can you split this off into its own component, which can be unit tested.

2022-02-07 16:30 UTC, YazeedLoonat commented on shared-helpers/src/catchNetworkError.ts
> +          : t("authentication.signIn.passwordOutdated"),
So we only flag `mfaEnabled` when we go to do the `onSubmitMfaCode` piece of this, and that means we already had gotten through a login attempt and been flagged for updating our password by the time we get there.

The only errors that should happen at that point are either mfacode isn't correct or something went wrong when trying to do the db wrties/reads

I tested this out by changing the password updated at column to be a year ago and at the enter email and password stage the person logging in is informed their password is out of date and they need to update it

2022-02-07 20:08 UTC, seanmalbert requested changes
@YazeedLoonat, 

A few more things:
1. there are a couple of translation strings where it says `Verify that its you`, that should read `it's you`
2. the email option for sending the code uses the "phone number" language
3. the email option for sending the code doesn't send an email with a code

2022-02-08 00:42 UTC, YazeedLoonat commented
Hey @seanmalbert this has been updated, lemme know what you think

2022-02-08 23:52 UTC, emilyjablonski commented on ui-components/src/page_components/sign-in/FormSignInMFACode.tsx
> +          <div className="text-center mt-6">
<img width="366" alt="Screen Shot 2022-02-08 at 4 52 22 PM" src="https://user-images.githubusercontent.com/65367387/153095414-863e4362-fafb-46ed-9f93-05d30969f33d.png">

I'm not seeing the edit phone number line here

2022-02-09 18:10 UTC, YazeedLoonat commented
@emilyjablonski @seanmalbert 
after talking with jesse, the flow of this should be:
the first time someone uses their phone number to do an mfa log in, they should have the ability to edit that phone number possibly repeatedly. 
In order to support that, I'm going to be adding a phone_number_verified column to the user table, which will default to false. Once the user successfully logs in using their phone number we will flag the verified column which will disallow editing the phone number through the request mfa pathway

2022-02-10 05:32 UTC, YazeedLoonat commented
@seanmalbert @emilyjablonski should be ready for re-review
lemme know what you think

2022-02-11 17:53 UTC, emilyjablonski commented
Newest set of changes LGTM! Would love @seanmalbert final sign off

2022-02-14 02:29 UTC, seanmalbert approved these changes
LGTM

2022-02-14 02:41 UTC, merged