1928/styling fixes
bloom-housing/bloom pull request #2532
Opened 2022-02-23 20:34 UTC by YazeedLoonat

## Issue Overview

This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/1928#issuecomment-1042525792)

- [x] This change addresses the issue in full

## Description
This should address the styling issues with the mfa pathways 

## How Can This Be Tested/Reviewed?
Go to the partner's site and log in as user with mfa enabled
as you go through the mfa process, verify that the styling matches what is in the mock, and in the comments of the ticket linked above

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [x] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

2022-02-24 21:38 UTC, YazeedLoonat commented
This should now also address the changes requested in:
https://github.com/bloom-housing/bloom/issues/1928#issuecomment-1050136761

2022-02-24 22:02 UTC, emilyjablonski requested changes
We're still missing the styling fixes for the box (the margin and the border not going all the way across) on the phone number page, on each page we have a gray border-b on the card we should remove. I'm also getting a 500 on phone number entry but we can continue to touch base offline there it might be a personal issue.

2022-02-24 22:04 UTC, emilyjablonski commented
<img width="528" alt="Screen Shot 2022-02-24 at 2 55 47 PM" src="https://user-images.githubusercontent.com/65367387/155615270-167e3a4d-8f0b-4670-879a-835341e4a49b.png">
If I enter an incorrect code I get an "email/password" error

2022-02-24 22:20 UTC, emilyjablonski commented on ui-components/src/global/forms.scss
> +.field-helper-element {
This doesn't seem to be used anywhere

2022-02-25 01:24 UTC, emilyjablonski requested changes
Some changes to make:
* We still need to remove the bottom border on all the cards - I hover over it at the end of the attached video if that helps!
* We still need to update the error message for an incorrect code to not show invalid email/password
* The edit phone number link is now cursor-pointer and focusable, but it is not actionable on enter and it's not in the right tab order - it is the first focusable element on the page
* If I enter the wrong code and try to enter a new one, the error message pops up again after the first valid keypress


https://user-images.githubusercontent.com/65367387/155635731-8be84a98-0ea4-45f8-8684-6dae245c617a.mov

Let me know if you wanna pair tomorrow!

2022-02-25 08:52 UTC, YazeedLoonat commented
Hey @emilyjablonski I think I got all your points now, thank you for the video it really helped me understand what you were pointing out

for `We still need to update the error message for an incorrect code to not show invalid email/password` I left the verbiage in for email and password, but added mfacode verbiage too when its appropriate. I remember from a previous conversation we were unsure if we wanted to obfuscate what was wrong with the login in request or not. I can change that if you think its better to specify that at that point its the code thats wrong

2022-02-25 18:39 UTC, emilyjablonski requested changes
We touched base offline, but:

- The borders and error message pop issues resolved and look great
- We're touching base with Jesse offline to confirm the error string
- After the latest set of changes I'm no longer able to change my phone number (below)
- Locking out after 5 failed codes is still letting me through once I enter a correct code (again sorry for not testing this flow earlier :( I didn't think it was meant to lock)

![Screen Shot 2022-02-25 at 11 33 43 AM](https://user-images.githubusercontent.com/65367387/155769583-ff5be1a2-26ae-4c4d-81d7-40e36f8324fe.png)

2022-02-25 19:39 UTC, emilyjablonski approved these changes
Pulling lockout issues into a separate ticket - once Jesse gets back about the error message GTM!

2022-02-25 23:14 UTC, emilyjablonski commented on ui-components/src/locales/general.json
> +      "enterValidEmailAndPasswordAndMFA": "Please enter a valid code",
Sorry to ask for such a small change but all of the other similar error strings end in a period - after that good to merge 🥳

2022-02-28 23:34 UTC, YazeedLoonat commented
Hey @seanmalbert could you peep this one, one last time please

2022-02-28 23:42 UTC, seanmalbert approved these changes
This looks good to me, I created [this issue](https://github.com/bloom-housing/bloom/issues/2547), to address partner users not being able to login to the public site.

2022-02-28 23:42 UTC, merged