Add terms content
bloom-housing/bloom pull request #2563
Opened 2022-03-09 16:53 UTC by dominikx96

# Pull Request Template

## Issue Overview

This PR addresses #2537

- [x] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

Adds a markdown content into the terms of use modal.

## How Can This Be Tested/Reviewed?

1. Open partners portal and /users/confirm?token=abc
2. Click on the "terms of use" link
3. Check the terms of use content and compare it with https://docs.google.com/document/d/1uvyO7PwrlBRQTlRQLGAYUD_PcS54nfzQ/edit

Describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [x] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

2022-03-10 21:44 UTC, emilyjablonski requested changes
Sorry for the confusion around this one, this has been a little tricky to set up - but we will want a different approach to this. We don't want the SJ copy to be in core, only in SJ, and we will want to store the terms in the DB on the jurisdiction entity with `partnerTerms` - so core would have lorem ipsum, and SJ would have its own DB string that is the new copy.

I think this means the core changes are: read from partnersTerms, set default in core to lorem ipsum, and keep the modal styling
And changes in SJ: Pull in the core changes, set the DB string to the new copy

Let me know if you want to shift the DB string work onto someone else's plate. Thanks!

2022-03-21 10:50 UTC, pbn4 commented
@emilyjablonski @dominikx96 I added add-jurisdiction-partner-terms migration to core backend to only set the necessary lorem ipsum and sj_terms.md strings. 

IIRC partners site is sourced from core repository so there are no changes required in housingbayarea repo, only a new migration here in core.

2022-03-22 00:01 UTC, seanmalbert commented
@dominikx96 and @pbn4 ,
Since we get the jurisdiction for partners from the user's jurisdictions we have two main options:

1. We expand on the idea of `isUserConfirmationTokenValid` found in https://github.com/bloom-housing/bloom/pull/2574, and if the token is valid, we can get the jurisdictions for a user (with a separate endpoint). I don't think it's a security risk to have an endpoint that returns the jurisdiction IDs associated with a user, given a token.

2.  We move the terms check to after the user logs in. This would require adding a flag to the database to check if the user has accepted the terms and until they do accept the terms, they would be presented with a screen to accept them before continuing forward, which would look something like:
![Screen Shot 2022-03-21 at 4 57 06 PM](https://user-images.githubusercontent.com/4401157/159381825-f6fb56d9-4810-46b9-95b3-6996a300d5a0.png)

Option two is my preference.

2022-03-22 00:01 UTC, seanmalbert commented
@dominikx96 and @pbn4 ,
Since we get the jurisdiction for partners from the user's jurisdictions we have two main options:

1. We expand on the idea of `isUserConfirmationTokenValid` found in https://github.com/bloom-housing/bloom/pull/2574, and if the token is valid, we can get the jurisdictions for a user (with a separate endpoint). I don't think it's a security risk to have an endpoint that returns the jurisdiction IDs associated with a user, given a token.

2.  We move the terms check to after the user logs in. This would require adding a flag to the database to check if the user has accepted the terms and until they do accept the terms, they would be presented with a screen to accept them before continuing forward, which would look something like:
![Screen Shot 2022-03-21 at 4 57 06 PM](https://user-images.githubusercontent.com/4401157/159381825-f6fb56d9-4810-46b9-95b3-6996a300d5a0.png)

Option two is my preference.

2022-04-04 15:25 UTC, dominikx96 commented
@slowbot I've updated terms content and made a form wider
![Screenshot 2022-04-04 at 17 21 09](https://user-images.githubusercontent.com/16655908/161577737-7c5bcc37-b1a3-4c99-8f66-f0bd3fcda7b1.png)

2022-04-04 21:52 UTC, emilyjablonski commented on sites/partners/cypress/integration/01-sign-in-terms.spec.ts
> +describe("Log in and accept terms", () => {
🥳

2022-04-04 22:01 UTC, emilyjablonski approved these changes
This looks great to me! I'd like Jesse's sign-off as well unless the timing is too tight.

2022-04-04 22:20 UTC, seanmalbert approved these changes
@dominikx96 , approved, but I do have two minor nitpicks noted in the comments that @slowbot can override.

2022-04-04 22:20 UTC, seanmalbert commented on backend/core/src/migration/1647858061141-add-jurisdiction-partner-terms.ts
> +
Visually, there doesn't end up being space here.
![Screen Shot 2022-04-04 at 3 13 45 PM](https://user-images.githubusercontent.com/4401157/161641225-b4af85b0-331a-4365-82fa-25f1b8dd4cc4.png)

2022-04-04 22:20 UTC, seanmalbert commented on ui-components/src/page_components/sign-in/FormTerms.tsx
> +        <div className="form-card__lead text-center">
My preference would be to not have the text centered. I think it makes it harder to read.

![Screen Shot 2022-04-04 at 3 16 52 PM](https://user-images.githubusercontent.com/4401157/161641280-e829be9e-5173-46e8-974f-bf0760120862.png)

vs

![Screen Shot 2022-04-04 at 3 17 00 PM](https://user-images.githubusercontent.com/4401157/161641303-429f3838-65a4-434a-aa3a-b9d130c57fb3.png)

2022-04-06 08:34 UTC, dominikx96 commented
@slowbot updated!

2022-04-06 21:48 UTC, seanmalbert commented
@slowbot , here's a screenshot of what it looks like now:
![Screen Shot 2022-04-06 at 2 47 55 PM](https://user-images.githubusercontent.com/4401157/162077537-a3f8a814-4b1a-485d-b49c-2250eee3d208.png)

2022-04-06 21:52 UTC, seanmalbert commented
![Screen Shot 2022-04-06 at 2 52 07 PM](https://user-images.githubusercontent.com/4401157/162078027-7c84ec5b-96f2-46e4-8f4d-ae00d65a47df.png)

2022-04-07 01:48 UTC, merged