fix: ux updates for new listing card design
bloom-housing/bloom pull request #2687
Opened 2022-04-23 01:39 UTC by emilyjablonski

# Pull Request Template

## Issue Overview

This PR addresses #issue

- [ ] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

Please include a summary of the change and which issue(s) is addressed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## How Can This Be Tested/Reviewed?

Provide instructions so we can review.

Describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have added QA notes to the issue with applicable URLs
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

2022-04-25 06:55 UTC, YazeedLoonat requested changes
Hey @emilyjablonski gonna put this in as a requested change but I might be wrong on it, so just let me know

On the details page on mobile I think the listing title isn't like justify center? hard to explain but it doesn't look like what I would expect given the mock (if that makes sense)

2022-04-25 15:18 UTC, emilyjablonski commented
![Screen Shot 2022-04-25 at 9 17 25 AM](https://user-images.githubusercontent.com/65367387/165119764-927feb1f-0068-4167-9c97-3bed74734d24.png)
@YazeedLoonat This is what I'm seeing on the mobile view which I think is what you mean, or is it something else?

2022-04-25 15:36 UTC, YazeedLoonat commented
Hey @emilyjablonski sorry I should have just included a link to what I was looking at: https://deploy-preview-2687--dev-bloom.netlify.app/listing/eef93126-08e1-48c2-880f-e6cfa54d19cc/test_default_lottery_results_pending_548_market_street_san_francisco_ca 

the title on that one doesn't seem to be centered although it could just be how long that title is

2022-04-25 17:04 UTC, emilyjablonski commented
@slowbot @YazeedLoonat Feedback should be addressed, would love your eyes again

2022-04-27 16:42 UTC, YazeedLoonat approved these changes
LGTM

2022-04-27 20:42 UTC, emilyjablonski commented
Just needs eyes from @slowbot

2022-04-29 16:27 UTC, merged