2128/alt contact street field 2
bloom-housing/bloom pull request #2697
Opened 2022-04-26 15:08 UTC by adriencyberspace

# Pull Request Template

## Issue Overview

This PR addresses #2128 

- [ ] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

This PR adds a second street field for unit / apt no. for alternate contact on the user form.

## How Can This Be Tested/Reviewed?

Entry Point: http://localhost:3000/applications/contact/alternate-contact-contact

1. Begin an application and select that you have an alternate contact
2. Fill out alternate contact's address and use the second street field (Apt or Unit #)
3. At the review section of the application, you will see your alt contact's full address
4. In partners, open your application and you will also see your alt contact's full address

![image](https://user-images.githubusercontent.com/60076088/165331779-3a090c62-d19b-4b09-988c-d8f31b5ac76a.png)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have added QA notes to the issue with applicable URLs
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

2022-04-26 20:23 UTC, emilyjablonski commented on ui-components/src/helpers/address.tsx
> +      {props.address.street2 && (
Address formats usually have street 2 on the same line, I actually just made this change in another PR I have up if you wanna take a look: https://github.com/bloom-housing/bloom/pull/2675/files#diff-850c89614d0470e86af5b2769705e03fad7e3869c92eb5eca4eb4025329b742aR1

2022-04-26 20:23 UTC, emilyjablonski requested changes
After the street2 multiline address formatting update, lgtm!

2022-04-27 17:33 UTC, emilyjablonski approved these changes
LGTM after the tests go green

2022-04-27 23:15 UTC, YazeedLoonat requested changes
Looks good, please update ui-component tests so they can pass

also in your qa notes the url should point to the dev site

2022-04-28 15:25 UTC, merged