fix: use appropriate copy for FCFS vs Lottery in Application Confirmation screen
bloom-housing/bloom pull request #2702
Opened 2022-04-27 22:43 UTC by jaredcwhite

# Pull Request Template

## Issue Overview

This PR addresses #2510 

- [x] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

In QA testing it was discovered the original PR #2558 only included copy for First Come First Serve listings. This updates the application confirmation screen so that Lottery listings will also show the correct copy.

## How Can This Be Tested/Reviewed?

TBD

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have added QA notes to the issue with applicable URLs
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

2022-04-29 19:50 UTC, emilyjablonski commented on sites/public/pages/applications/review/confirmation.tsx
> +      if (listing.reviewOrderType == ListingReviewOrder.lottery) {
A listing can be saved as having a review order type of lottery and no application due date, so the existence of that field should also be checked so we can't end up in a broken string state.

2022-04-29 19:51 UTC, emilyjablonski requested changes
Check out the comment above around checking for the string fields before using them

2022-04-30 00:11 UTC, jaredcwhite commented
> Check out the comment above around checking for the string fields before using them

Good to know! I think this will effect the emails that go out as well so I'll also look that over again.

2022-05-03 20:28 UTC, jaredcwhite commented
All right, I should have that handled now. I'm not sure if published lottery listings do happen to go out without a due date present, but if that's an issue probably needs to get handled on the backend validation side of things.

2022-05-04 20:22 UTC, emilyjablonski approved these changes
LGTM!

2022-05-05 02:25 UTC, merged