2681/app back button
bloom-housing/bloom pull request #2704
Opened 2022-04-28 18:40 UTC by adriencyberspace

# Pull Request Template

## Issue Overview

This PR addresses #2681

- [X] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

This fixes the back button on the /contact/address page of the application listing. Because both the address form and the verify address form share a url, the back button for both views takes you back to the previous url: /contact/name. This fixes the button so that if you are on the verify form page, the back button takes you back to the address form page, but if you are on the address form page, the back button takes you to the previous url. 

## How Can This Be Tested/Reviewed?

1. Click any listing in public and apply online
2. Once you reach the /applications/contact/address page, fill out the form and click next
3. Once on the verify address page, click back
4. You will be taken back to the correct view - the one you just came from. All of your info will still be populated
5. Click back again and you will be on the /applications/contact/name page 

Describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have added QA notes to the issue with applicable URLs
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

2022-04-28 19:58 UTC, emilyjablonski commented
I'd check out the failing Cypress test, it seems like it may be related

2022-04-28 22:58 UTC, adriencyberspace commented
Don't merge! Debugging.

2022-05-02 19:13 UTC, adriencyberspace commented
@emilyjablonski Should be fixed now. The problem was in using conductor.currentStep.url instead of window.location.pathname or hardcoding the url. Any idea why that is?

2022-05-04 19:55 UTC, YazeedLoonat requested changes
Looks good, I think it would be better to switch to using the react hooks for these instead

2022-05-04 19:55 UTC, YazeedLoonat commented on sites/public/pages/applications/contact/address.tsx
> +          url={verifyAddress ? window.location.pathname : conductor.determinePreviousUrl()}
can this use the useMemo hook instead

2022-05-04 19:55 UTC, YazeedLoonat commented on sites/public/pages/applications/contact/address.tsx
> +            verifyAddress ? () => setVerifyAddress(false) : () => conductor.setNavigatedBack(true)
can this use the callback hook instead

2022-05-07 18:20 UTC, YazeedLoonat approved these changes
LGTM

2022-05-09 14:02 UTC, merged