2723/listing availability listing browse
bloom-housing/bloom pull request #2739
Opened 2022-05-18 21:02 UTC by YazeedLoonat

## Issue Overview

This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/2723)

- [x] This change addresses the issue in full

## Description
This adds label on the public sites listing browse page to include the new listing availability

## How Can This Be Tested/Reviewed?
head to __partner
create or edit a listing and set it to have its availability as `Available Units`
create or edit a second listing to have its availability set to `Open Waitlist`

head to __public 
head to the browse page 
verify that the labels are present like they should be

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have added QA notes to the issue with applicable URLs
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [x] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [x] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [x] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

2022-05-23 16:58 UTC, emilyjablonski commented on backend/core/src/listings/listings.service.ts
> +      if (listingDto.listingAvailability === ListingAvailability.availableUnits) {
Can we just check the units length once, instead of incrementing on each unit?

2022-05-23 16:58 UTC, emilyjablonski commented on backend/core/src/migration/1652833763955-add-listing-availability-field.ts
> +      `ALTER TABLE "jurisdictions" ALTER COLUMN "rental_assistance_default" DROP DEFAULT`
Is this related to the PR?

2022-05-23 17:00 UTC, emilyjablonski requested changes
https://github.com/bloom-housing/bloom/pull/2740

I have the same comments here as I do above (seems to be a lot of duplicated changes between these two as a heads up, maybe to prevent having to make the changes on all three PRs, we could have a base PR that adds the field?)

2022-05-25 18:03 UTC, YazeedLoonat commented
closing as https://github.com/bloom-housing/bloom/pull/2740 was merged in

2022-05-26 18:48 UTC, emilyjablonski commented
@YazeedLoonat Just want to confirm we can close this?

2022-05-26 19:13 UTC, YazeedLoonat commented
closing as: https://github.com/bloom-housing/bloom/pull/2740 was merged in

2022-05-26 19:13 UTC, closed without merging