feat(modal): add option for fixed-height scrollable modal
bloom-housing/bloom pull request #2769
Opened 2022-05-31 16:02 UTC by jacksongonzales

# Pull Request Template

## Issue Overview

This PR addresses [DAH-1157](https://sfgovdt.jira.com/jira/software/c/projects/DAH/boards/122?modal=detail&selectedIssue=DAH-1157)

## Description

We need to approximate the appearance of the lottery results modal on the angular version of DAHLIA. This PR adds an optional prop `scrollable` that makes the modal a fixed height and scrollable for long body content.

## How Can This Be Tested/Reviewed?

Run storybook and open the scrollable modal story

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have added QA notes to the issue with applicable URLs
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

2022-05-31 23:37 UTC, christine-sfg commented on ui-components/src/overlays/Modal.tsx
> +        <section className={classNames.join(" ")}>
would it be helpful to add classnames as a prop or is it unnecessary?

2022-05-31 23:37 UTC, christine-sfg commented on ui-components/src/overlays/Modal.tsx
> +        <section className={classNames.join(" ")}>
would it be helpful to add classnames as a prop or is it unnecessary?

2022-05-31 23:40 UTC, emilyjablonski commented on ui-components/src/overlays/Modal.scss
> +    height: 80vh;
![Screen Shot 2022-05-31 at 5 27 26 PM](https://user-images.githubusercontent.com/65367387/171300956-c5345063-ef1b-4695-9b46-a2b146a75fc0.png)
This style can result in the footer being cut off at small screen sizes. Some sort of calc based on the view height I think will prevent this, something like `max-height: calc(100vh - 200px)` - let me know what you think!

2022-05-31 23:41 UTC, emilyjablonski requested changes
I like the new prop and story! I've got one comment on some height styling, and then I think as part of the DAH ticket we need the ability to add some class names to allow for reduced padding / margin. Let me know if you'd like to do this in a separate ticket.

2022-06-02 21:47 UTC, christine-sfg approved these changes

2022-06-04 00:47 UTC, emilyjablonski approved these changes

2022-06-04 00:47 UTC, merged