fix(login): too many login attempts fix
bloom-housing/bloom pull request #2988
Opened 2022-08-23 17:22 UTC by ludtkemorgan

# Pull Request Template

## Issue Overview

This PR addresses #2903 

- [x] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

This PR fixes the incorrect implementation of entering the wrong password too many times. Currently the incorrect count is getting updated correctly and also resetting correctly when a user finally signs in correctly. However, the last login time is not getting updated so the check for if they have waited the 30 minutes is always passing. 

Also this updates the UI to read the remaining attempt count in the error message displayed.
![image](https://user-images.githubusercontent.com/42942267/186223760-4b93d26b-9399-46d7-a02c-c4e78362b532.png)

## How Can This Be Tested/Reviewed?

On the sign in page attempt to log in with a valid email (known user) but the incorrect password. Should get the error message with "5" failed attempts.

Repeat 4 more times and the error message should increment down.

On the sixth wrong one the lockout error should appear and not able to login or get the original error message for an additional 30 minutes.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have added QA notes to the issue with applicable URLs
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [x] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [x] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

## QA Notes:

*When testing in Dev be cognizant of locking out shared accounts.*
 On the sign in page attempt to log in with a valid email (known user) but the incorrect password. Should get the error message with "5" failed attempts.

Repeat 4 more times and the error message should increment down.

On the sixth wrong one the lockout error should appear and not able to login or get the original error message for an additional 30 minutes.

2022-08-24 00:23 UTC, seanmalbert approved these changes
Looks good, @ludtkemorgan. Can you add another test that ensures the user can login after the retryAfter period?

And for anyone else who is reviewing you can test the retry after updating last_login_at with `update user_accounts set last_login_at = now() - interval '30 MINUTES' where id = 'your id'`

2022-08-24 16:10 UTC, emilyjablonski approved these changes
LGTM! Do you mind filling out the PR checklist (includes adding QA Notes to the issue)

2022-08-24 16:50 UTC, YazeedLoonat requested changes
looks good, only one small thing I found, during the mfa flow when incorrect attempts are made the count of failed attempts on the front end warning does not count down correctly

2022-08-25 20:13 UTC, ludtkemorgan commented
@YazeedLoonat I believe I have fixed the issue for the MFA path

2022-08-30 21:06 UTC, YazeedLoonat approved these changes
LGTM

2022-08-30 21:25 UTC, merged