fix: return N/A if rent and income is NaN
bloom-housing/bloom pull request #3040
Opened 2022-09-06 06:48 UTC by KrissDrawing

# Pull Request Template

## Issue Overview

This PR addresses #3035

- [x] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

While not passing rent and income values, we've sent probably `null` value that was processed anyway as valid number, so while formatting `parseFloat` returned `NaN`.
Now instead of `$NaN per month` it displays as `N/A per month` etc.
Not sure if that should also contain `$` before `N/A`

## How Can This Be Tested/Reviewed?

We need to have listing where in listing units we select nothing in `How is Rent Determined?`. While editing listing just remove existing values, at first it can throw error while saving, but after open listing unit and saving it again it should work fine.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have added QA notes to the issue with applicable URLs
- [x] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

2022-09-06 17:37 UTC, emilyjablonski commented on backend/core/src/shared/units-transformations.ts
> +  if (Number.isNaN(roundedValue)) return "N/A"
If we return this string in English here, the translations won't come through. We may need to pass just the key (`"t.n/a"`) (like we are doing here: https://github.com/bloom-housing/bloom/blob/dev/ui-components/src/tables/StandardTable.tsx#L155) and translate on the frontend (which we allow here: https://github.com/bloom-housing/bloom/blob/dev/ui-components/src/tables/StandardTable.tsx#L155)

2022-09-06 17:37 UTC, emilyjablonski requested changes
Just need to be able to support translations! Context above

2022-09-08 23:20 UTC, emilyjablonski commented
<img width="654" alt="Screen Shot 2022-09-08 at 7 19 55 PM" src="https://user-images.githubusercontent.com/65367387/189242290-96318b95-cfaa-477b-92c6-e11d6640403a.png">
translations are coming through now, thank you! the last update will be that we don't want the `per month` string in these `n/a` cases

2022-09-12 15:33 UTC, seanmalbert approved these changes

2022-09-13 15:51 UTC, merged