feat: new listing type field
bloom-housing/bloom pull request #3085
Opened 2022-09-23 19:21 UTC by emilyjablonski

# Pull Request Template

## Issue Overview

This PR addresses #issue

- [ ] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

Please include a summary of the change and which issue(s) is addressed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## How Can This Be Tested/Reviewed?

Provide instructions so we can review.

Describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have added QA notes to the issue with applicable URLs
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

2022-09-28 20:52 UTC, ColinBuyck approved these changes
LGTM! Felt a bit out of my element while reviewing some of the backend code pieces but functionally, this looks great 🥳

2022-09-28 22:31 UTC, jaredcwhite approved these changes
LGTM! 👍

2022-09-28 22:31 UTC, emilyjablonski commented
@YazeedLoonat Would love your eyes here particularly on the migration! 😀

2022-10-03 15:38 UTC, YazeedLoonat requested changes
looks good! one question and 2 small adjustments to the migration

should the coliseum listing have 
![image](https://user-images.githubusercontent.com/10088764/193618174-dd43423c-aeb5-44c5-adb5-e158dbc5ea42.png)
 even though its not marked as having a lottery?

2022-10-03 15:38 UTC, YazeedLoonat commented on backend/core/src/migration/1663959354563-new-listing-type-enum.ts
> +    const listings = await queryRunner.query(`SELECT * FROM listings`)
we probably don't want to select * here, can select the columns we need instead

2022-10-03 19:28 UTC, YazeedLoonat approved these changes
LGTM

2022-10-03 19:33 UTC, merged

2022-10-03 19:33 UTC, emilyjablonski commented
Oh sorry realizing I never touched on the waitlist string comment! That's the behavior on dev atm :)