feat: upgrading typeorm
bloom-housing/bloom pull request #3340
Opened 2023-02-20 06:35 UTC by YazeedLoonat

# Pull Request Template

## Issue Overview

This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/3184)

- [x] This change addresses the issue in full

## Description
This PR upgrades TypeORM to a much newer version

## How Can This Be Tested/Reviewed?
To be honest every part of the system needs to be tested:
**listings**
creating, editing, viewing (public and partners)
**applications**
creating, editing, viewing (public and partners
**users**
creating, editing, viewing
**duplicate listings**
resolving, marking as duplicate, viewing

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have added QA notes to the issue with applicable URLs
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have assigned reviewers
- [x] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [x] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [x] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

2023-02-21 07:10 UTC, YazeedLoonat commented on backend/core/src/migration/1676354438563-typeorm-upgrade.ts
> +        await queryRunner.query(`ALTER TABLE "listings" ALTER COLUMN "last_application_update_at" SET DEFAULT '1970-01-01'`);
I think it should although I think the migration reset would have addressed it for that PR

2023-02-21 07:14 UTC, YazeedLoonat commented on backend/core/src/seeder/seed.ts
> +      const roles: UserRoles = { user: agent, isPartner: true, userId: undefined }
nice catch! so TypeORM changed how relationships are defined, and now there must be an explicit column (that should match up with the foreign key ) 

if you check the entity definition you should see the update represented there. From what I understood this makes piecing things together by the relationship a little be easier for TypeORM

2023-02-21 07:22 UTC, YazeedLoonat commented on backend/core/package.json
> +    "@nestjs/common": "9.3.7",
good catch will update!

2023-02-21 15:48 UTC, seanmalbert requested changes

2023-02-21 15:48 UTC, seanmalbert commented on backend/core/src/auth/helpers/user-helpers.ts
> +}
Question (blocking): Do these need to live outside of the user service? For the use cases outside of the user service (like the authz service), isn't it nest js best practice to inject the user service?

2023-02-21 15:48 UTC, seanmalbert commented on backend/core/src/auth/services/authz.service.ts
> +        const accessedUser = await findById(this.userRepository, obj.id)
Suggestion (blocking): If you move `findById` to the user service and inject that (which should already inject the user repo), then this should become simplified and you won't have to pass around the user repo.

2023-02-21 15:48 UTC, seanmalbert commented on backend/core/src/auth/services/user.service.ts
> +} from "../helpers/user-helpers"
Suggestion (blocking): move these into the user service.

2023-02-21 15:48 UTC, seanmalbert commented on backend/core/src/listings/db/listing-helpers.ts
> +}
Suggestion (blocking): similar to the user service comments, recommend these get moved into the listing service.

2023-02-22 16:09 UTC, ludtkemorgan commented on backend/core/package.json
>      "@nestjs/throttler": "^2.0.0",
Github won't let me comment on the correct line, but shouldn't this PR be upgrading `typeorm` on line 85?

2023-02-22 19:04 UTC, emilyjablonski commented
@YazeedLoonat Any remaining concerns post-bash yesterday? Are you looking for more partners bashing on the preview link?

2023-03-07 23:31 UTC, ludtkemorgan commented
@YazeedLoonat I got the backend tests to work. However, I just noticed that there is a skipped test that is failing for the same reason that the Assets one was. And the solution I did for the Assets won't work for the afs tests. Still digging into that now

2023-03-08 16:49 UTC, emilyjablonski commented
I think there are still bugs from bash to resolve (maybe? @YazeedLoonat)

2023-03-13 16:29 UTC, emilyjablonski commented
@YazeedLoonat Just confirming, I think this one is not ready yet, is that right?

2023-03-21 22:43 UTC, YazeedLoonat commented
@emilyjablonski @seanmalbert @ColinBuyck @ludtkemorgan 
Hey everyone, made updates across a lot of this PR if you wanna give it another go
🤞 everything should be working on this one!

2023-03-21 23:02 UTC, emilyjablonski commented
@YazeedLoonat Looks like it's not building as a heads up!

2023-03-29 22:34 UTC, YazeedLoonat commented
Update on this one:

Currently this will need to be put on pause. 
We ran into an issue where the JurisdicitionResolverService used in the Email Service is not available (either by the automatic nest js instantiation step, or using ModuleRef.resolve)

The most likely cause of this is a circular dependency issue that we have throughout the application.

From looking at NestJS documentation particularly (https://docs.nestjs.com/fundamentals/circular-dependency) we have both circular dependencies and leverage a per request scope. 
https://github.com/nestjs/nest/issues/5778

This combination is something Nest does not support, and we would need to refactor our backend to either get rid of the per request scope, or the leveraging of circular dependencies. 

Either rewrite is likely a large effort and so a spike ticket has been written up to look into these options.

2023-04-18 00:26 UTC, seanmalbert commented
> Update on this one:
> 
> Currently this will need to be put on pause. We ran into an issue where the JurisdicitionResolverService used in the Email Service is not available (either by the automatic nest js instantiation step, or using ModuleRef.resolve)
> 
> The most likely cause of this is a circular dependency issue that we have throughout the application.
> 
> From looking at NestJS documentation particularly (https://docs.nestjs.com/fundamentals/circular-dependency) we have both circular dependencies and leverage a per request scope. [nestjs/nest#5778](https://github.com/nestjs/nest/issues/5778)
> 
> This combination is something Nest does not support, and we would need to refactor our backend to either get rid of the per request scope, or the leveraging of circular dependencies.
> 
> Either rewrite is likely a large effort and so a spike ticket has been written up to look into these options.
> 
> [nestjs/nest#5487](https://github.com/nestjs/nest/issues/5487) is a similar issue to what we are running into, strict mode was not the solution

@YazeedLoonat , I did not run into this issue. I did run into a small issue in the jurisdiction resolver service and fixed it. Locally, I'm able to login with MFA with both email and sms.

2023-05-05 18:31 UTC, ludtkemorgan requested changes
I haven't found any functional issues, but still investigating how to solve that broken skipped test. There is a chance the AFS code has an issue, but more likely we just need to update the test somehow

2023-05-05 18:31 UTC, ludtkemorgan commented on backend/core/test/afs/afs.e2e-spec.ts
> +describe.skip("ApplicationFlaggedSets", () => {
We should probably figure out how to resolve the issues with this test rather than skipping it

2023-05-05 18:31 UTC, ludtkemorgan commented on backend/core/test/afs/afs.e2e-spec.ts
> +describe.skip("ApplicationFlaggedSets", () => {
Taking a quick pass over it, it looks like there are two issues. One is an easy fix that will solve the logger issue. The other one might be a bit tougher that is either a fix to the test or there is potentially an actual bug in the cron job code

2023-05-08 23:24 UTC, YazeedLoonat commented
@ludtkemorgan @seanmalbert @emilyjablonski @ColinBuyck this should be ready for re-review now!

2023-05-12 18:56 UTC, ludtkemorgan approved these changes
🦖 🌮

2023-05-15 17:57 UTC, ColinBuyck commented
@YazeedLoonat do you mind resolving the merge conflicts when you get a chance? Hoping to test this with listings export!

2023-05-15 19:53 UTC, YazeedLoonat commented
hey @ColinBuyck merge conflicts have been resolved, lemme know what you think

2023-05-15 21:18 UTC, ColinBuyck requested changes
I'm unfortunately getting a 500 when attempting to resolve an application set
<img width="1440" alt="Screenshot 2023-05-15 at 2 16 40 PM" src="https://github.com/bloom-housing/bloom/assets/53269332/3dc27412-828b-4222-8ee5-59f4634a8e90">

2023-05-17 16:02 UTC, YazeedLoonat commented
Hey @ColinBuyck this should be good to go again

2023-05-18 16:36 UTC, ColinBuyck approved these changes
LGTM 🍌  I rate this 12/10!

2023-05-22 16:01 UTC, merged