3291/listing export take 2
bloom-housing/bloom pull request #3424
Opened 2023-05-03 01:54 UTC by ColinBuyck

# Pull Request Template

## Issue Overview

This PR addresses #3291 

- [x] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

Please include a summary of the change and which issue(s) is addressed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## How Can This Be Tested/Reviewed?

Provide instructions so we can review.

Describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have added QA notes to the issue with applicable URLs
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

2023-05-05 22:02 UTC, emilyjablonski requested changes
Looking good! Just a few notes:
* In the status column I'm seeing "Public" or empty, could be intentional but might have assumed there would be different text in the draft state
* `Are postmarks considered?` isn't populating even if there is data

2023-05-05 22:06 UTC, ludtkemorgan requested changes

2023-05-05 22:14 UTC, ludtkemorgan commented on backend/core/src/listings/listings.service.ts
> +      .andWhere("userRole.is_admin = :is_admin", { is_admin: true })
Found another bug. Since this is just `is_admin` if you are a jurisdictional admin the button is there but the call to the backend fails

2023-05-06 00:15 UTC, ColinBuyck commented
@emilyjablonski @ludtkemorgan Thank you both for the review! I've fixed the postmark issue and made the decision to shift "Are postmarks considered?" to just "Postmark" and show either the date or nothing. This mirrors the pattern used in Detroit. Do you have any concerns with this change @sarahlazarich?

As for the empty status, I realized I forgot to cover the closed state and that should be covered now! Good catch :fishsticks:

For the jurisdictional admin piece, I made a bigger change to address that the story says "As a jurisdictional admin OR an admin in partners portal". The export should now function for both roles and will only show the permissioned listings for the respective user.

2023-05-08 14:26 UTC, ludtkemorgan approved these changes
🚈

2023-05-08 15:27 UTC, emilyjablonski approved these changes
🍭

2023-05-09 15:54 UTC, sarahlazarich commented
no concerns with that change @ColinBuyck !

2023-05-10 17:59 UTC, merged