fix: validate url field in building section criteria
bloom-housing/bloom pull request #3460
Opened 2023-05-23 15:07 UTC by KrissDrawing

# Pull Request Template

## Issue Overview

This PR addresses #3422 

- [ ] This change addresses the issue in full
- [x] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

its part of task that will trigger validation from `url` type field. 
Needs UIC change from [here](https://github.com/bloom-housing/ui-components/pull/110)

## How Can This Be Tested/Reviewed?

Go to partners site edit listing and `building section criteria` url will now be validated on save.
Also pdf save part of `building section criteria` should still work like before.

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have added QA notes to the issue with applicable URLs
- [x] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

2023-05-25 19:38 UTC, ludtkemorgan submitted a review, later dismissed

2023-05-25 19:38 UTC, ludtkemorgan commented on sites/partners/page_content/locale_overrides/general.json
> +  "errors.urlHttpsError": "Url requires https://",
Also, with this change now all url regex issues has this error message. So if it's an invalid url, but has the `https://` the error message could be a bit confusing
![image](https://github.com/bloom-housing/bloom/assets/42942267/e830f546-b4f3-44b8-a3a4-3bfa094abf31)

2023-05-30 15:12 UTC, KrissDrawing commented on sites/partners/page_content/locale_overrides/general.json
> +  "errors.urlHttpsError": "Url requires https://",
@ludtkemorgan good catch 👍 I added 2 types of validation in UIC part so now if it has `https//:` or `http//:` it will throw `errors.urlError` message

2023-06-01 19:57 UTC, emilyjablonski requested changes
![Screenshot 2023-06-01 at 1 45 23 PM](https://github.com/bloom-housing/bloom/assets/65367387/7b5ac713-fb43-4e59-89cb-41aa3bb19e48)
The building selection criteria has this URL placeholder text but the other URL fields do not. We should be consistent and add it everywhere. I'm also not getting this validation on the building selection criteria field if I try to submit a listing with incorrect formatting. 

There is also a URL field within the settings page for programs/preferences, we should add this URL type there as well.

2023-06-15 16:27 UTC, KrissDrawing commented
description updated for newest changes

2023-06-16 16:08 UTC, emilyjablonski approved these changes
Thanks for your work on this! Linking the followup here: https://github.com/bloom-housing/bloom/issues/3510

2023-06-16 21:10 UTC, ColinBuyck reviewed
Everything LGTM 🟠 just one tiny question! I'm noticing that this allows for http:// in addition to https://, and the messaging only specifies https:// so just wanted to make sure that that behavior works for you @sarahlazarich. (cc: @emilyjablonski since I know you've dug into this one a bit)

2023-06-16 21:15 UTC, ColinBuyck approved these changes
Good to merge once that small question is confirmed 🖥️

2023-06-16 21:16 UTC, sarahlazarich commented
I think that's fine @ColinBuyck

2023-06-16 21:17 UTC, ColinBuyck commented
Sweet, thank you @sarahlazarich! This is ready to merge then @KrissDrawing

2023-06-21 16:03 UTC, merged