fix: switch to HTML text inputs with numeric validation
bloom-housing/bloom pull request #4128
Opened 2024-06-11 03:06 UTC by jaredcwhite

This PR addresses https://github.com/metrotranscom/doorway/issues/658

- [x] Addresses the issue in full
- [ ] Addresses only certain aspects of the issue

## Description

The working theory is the issue with numbers changing randomly in the unit editing is due to `input type="number"` weirdness around mouse/trackpad scrolling. This PR switches to `input type="text"` and uses React Hook Form validation to verify integer input.

## How Can This Be Tested/Reviewed?

Try editing units for a listing, income, or the miles radius on preferences.

## Author Checklist:

- [ ] Added QA notes to the issue with applicable URLs
- [x] Reviewed in a desktop view
- [x] Reviewed in a mobile view
- [x] Reviewed considering accessibility
- [ ] Added tests covering the changes
- [ ] Made corresponding changes to the documentation
- [ ] Ran `yarn generate:client` and/or created a migration when required

## Review Process:

- Read and understand the issue
- Ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very small remaining changes, if you don't need to re-review after the updates

2024-06-11 18:38 UTC, jaredcwhite commented
Cypress test failing seems to just be a glitch

2024-06-12 19:41 UTC, emilyjablonski commented on sites/partners/src/components/settings/PreferenceDrawer.tsx
> +                        validation={{ required: true, min: 0, pattern: /^[0-9.]+$/ }}
What might min do here now that it's text?

2024-06-12 19:43 UTC, emilyjablonski requested changes
After this change, I'm able to type letters into these numeric inputs, which I think we ideally want to avoid.

2024-06-28 19:40 UTC, jaredcwhite commented
I've updated the PR with a combination of currency-specific fields and text fields with numeric validation. Only the currency fields expressively forbid typing letters, and they also have the byproduct of forcing decimal places (aka `500.00` rather than `500`) which I'm concerned by cause trickle-down issues with display in other places. So…I'm not entirely sure we should consider this mergable without a broader convo.

2025-06-19 10:37 UTC, mcgarrye commented
Is this PR still valid? If so, can we get it caught up to main and I can review Monday

2025-06-25 02:03 UTC, jaredcwhite commented
@mcgarrye Because of the change where the decimal places are forced as mentioned above (typing 500 yields 500.00), I don't think we should merge this without discussing the possible ramifications.

2026-06-11 21:04 UTC, closed without merging