feat: listing duplication endpoint
bloom-housing/bloom pull request #4307
Opened 2024-09-05 18:53 UTC by mcgarrye

This PR addresses [#(799)](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/metrotranscom/doorway/799)

- [ ] Addresses the issue in full
- [ ] Addresses only certain aspects of the issue

## Description

Allows user to call `listings/duplicate` endpoint to create a copy listing from an existing listing.

## How Can This Be Tested/Reviewed?

Run partner portal and api and login as a admin/jadmin/partner user.
Have the listing id for the listing you would like to duplicate.
Fill out the payload for `listings/duplicate`. Set storedListing.id to the above.
Cases:

1. Set name to a unique name, set includeUnits to true. Should create a new draft listing with the name given which is otherwise identical to the original listing, including the units.
2. Set name to a unique name, set includeUnits to false. Should create a new draft listing with the name given which is otherwise identical to the original listing, excluding the units.
3. Set name to a the same name as the original listing. Should error with 400 BadRequest and a message 'New listing name must be unique'.

You can view the newly created in the Partners Portal

## Author Checklist:

- [ ] Added QA notes to the issue with applicable URLs
- [ ] Reviewed in a desktop view
- [ ] Reviewed in a mobile view
- [ ] Reviewed considering accessibility
- [ ] Added tests covering the changes
- [ ] Made corresponding changes to the documentation
- [ ] Ran `yarn generate:client` and/or created a migration when required

## Review Process:

- Read and understand the issue
- Ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very small remaining changes, if you don't need to re-review after the updates

2024-09-05 20:01 UTC, ColinBuyck commented on api/src/services/listing.service.ts
> +        storedListing.listingMultiselectQuestions?.map((question) => {
Nit: Could we use that =>({}) syntax brought up in yesterdays huddle?

2024-09-05 20:02 UTC, ColinBuyck commented on api/src/services/listing.service.ts
> +      lotteryLastRunAt: undefined,
Just merged in a PR adding lotteryLastPublishedAt field which should be set to undefined here too

2024-09-05 20:04 UTC, ColinBuyck commented on api/test/integration/listing.e2e-spec.ts
> +  describe('duplicate endpoint', () => {
Nit: Can these be separated to improve readability on if both duplication calls are broken or if it is dependent on the units piece?

2024-09-05 20:06 UTC, ColinBuyck approved these changes
LGTM 🫕 Just a few nits

2024-09-06 19:52 UTC, YazeedLoonat requested changes
looks good, some changes requested!

2024-09-06 19:52 UTC, YazeedLoonat commented on api/.env.template
> +ALLOW_PARTNERS_TO_CREATE_DUPLICATES=FALSE
can we change this to `ALLOW_PARTNERS_TO_DUPE_LISTINGS` or something like that, to make it clear that this is about duplicating listings

2024-09-06 19:52 UTC, YazeedLoonat commented on api/src/services/listing.service.ts
> +    if (dto.name.trim() === storedListing.name) {
can you move this to right after we get the stored listing, so we error early and don't do more work than we need to

2024-09-10 18:04 UTC, ColinBuyck approved these changes
Yahoooo 🪨

2024-09-10 18:10 UTC, merged