Add StatusAside component and place on the New/Edit Application form
bloom-housing/bloom pull request #917
Opened 2020-12-15 22:07 UTC by jaredcwhite

Close #696

@dominikx96 I added the new component to the sidebar, let me know what you think/

@slowbot Right now this is a single column, but it supports two-column button placements as well for more advanced layouts.

2020-12-16 15:33 UTC, dominikx96 commented on shared/ui-components/src/notifications/StatusAside.tsx
> +        <h3 className="status-aside__title">Status History</h3>
Can we use translated strings only?

2020-12-16 15:51 UTC, dominikx96 requested changes
@jaredcwhite noticed some things:

- StatusAside.tsx & StatusMessage.tsx have hardcoded strings, can we use translated strings?
- The StatusAside component doesn't support single children with e.g.: "Last updated: XXX", "Status History" is always visible. @slowbot do we plan to keep only this version or "minimal" variant should be available as well?

2020-12-17 00:14 UTC, jaredcwhite commented
> @jaredcwhite noticed some things:
> 
> * StatusAside.tsx & StatusMessage.tsx have hardcoded strings, can we use translated strings?
> * The StatusAside component doesn't support single children with e.g.: "Last updated: XXX", "Status History" is always visible. @slowbot do we plan to keep only this version or "minimal" variant should be available as well?

Both good points, thanks. I'd gotten both variants working for StatusMessage already, I think I just need to enhance StatusAside to support those.

2020-12-19 00:50 UTC, jaredcwhite commented
I made some changes so that the "Status History" title is part of the StatusMessages component, rather than the StatusAside component. I think this makes more sense, but let me know if you think there's a better way to do things.

2020-12-21 09:34 UTC, dominikx96 approved these changes
@jaredcwhite noticed hardcoded "Last Updated:" string inside StatusMessage.tsx - if we fix it LGTM and I think we can merge it :)

2020-12-21 22:11 UTC, merged